#!/bin/bash
# Configuration variables for the scaffolding.
#
# This script should likely work on any Linux flavor that is managed by an APT
# based package manager (should be easy to modify for other non-deb flavors).
#
# To reinstall any component of these base build tools, simply remove the
# folders and download files for the given product and re-execute this script.
#
# Copyright (c) 2013 Jordon Mears.
#
# Web Application Scaffolding is made available under the MIT license.
# <http://opensource.org/licenses/MIT>

# Where to download and install dependencies.
USER=`whoami`
WAS_DEPS="/home/$USER/.was/deps"

# Comma separated list of Javascript application namespaces.
JS_NAMESPACE=""

# Build and dist base.
BUILD_BASE="/home/$USER/.was"

# Make sure this executes correctly on a Mac.
if [ `uname` == 'Darwin' ]; then
  WAS_DEPS="/Users/$USER/.was/deps"
  BUILD_BASE="/Users/$USER/.was"
fi
