#!/bin/bash
# Web App Scaffolding
#
# This folder structure and set of scripts provides a framework for building,
# compiling, running and deploying web applications. See the readme.md files
# throughout the framework for details.
#
# Copyright (c) 2013 Jordon Mears.
#
# Web Application Scaffolding is made available under the MIT license.
# <http://opensource.org/licenses/MIT>

cd `dirname $0`

case "$1" in
  build)
    find ./scripts/build.d/ -name "*.sh" | sort | xargs -I % bash "%" "$@"
    ;;
  clean)
    find ./scripts/clean.d/ -name "*.sh" | sort | xargs -I % bash "%" "$@"
    ;;
  clone)
    find ./scripts/clone.d/ -name "*.sh" | sort | xargs -I % bash "%" "$@"
    ;;
  deploy)
    find ./scripts/deploy.d/ -name "*.sh" | sort | xargs -I % bash "%" "$@"
    ;;
  lint)
    find ./scripts/lint.d/ -name "*.sh" | sort | xargs -I % bash "%" "$@"
    ;;
  sample)
    find ./scripts/sample.d/ -name "*.sh" | sort | xargs -I % bash "%" "$@"
    ;;
  run)
    find ./scripts/run.d/ -name "*.sh" | sort | xargs -I % bash "%" "$@"
    ;;
  search)
    grep -rni --exclude-dir=thirdparty \
      --exclude-dir=build --exclude-dir=dist --exclude-dir=.git $2 .
    ;;
  test)
    find ./scripts/test.d/ -name "*.sh" | sort | xargs -I % bash "%" "$@"
    ;;
  *)
    echo "USAGE: was ACTION [OPTION]..."
    ;;
esac
